name: DiffuseSynthAPI_env
channels:
  - defaults
dependencies:
  - python=3.11.0
  - pip
  - jupyter
  - pip:
      - torch==2.0.1
      - git+https://github.com/huggingface/diffusers.git
      - transformers
      - fastapi
      - uvicorn
      - pydantic
      - accelerate
      - soundfile
      - pyinstaller